# Generated by Django 5.0.1 on 2024-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_highest_bid_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.DeleteModel(
            name='bid',
        ),
    ]
